name: Bug Report
description: File a bug report
title: "[Bug]: Failed test for CityTest.countryCitiesTest"
labels: ["bug", "triage"]
assignees:
  - RafCas88
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: raffaele.castaldo88@gmail.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "Failed test in CityTest.countryCitiesTest:85 expected: <String returned> but was: <null>"
    validations:
      required: true
  - type: textarea
    id: bug-fix
    attributes:
      label: Bug fix
      description: How did you fix the issue?
      placeholder: Tell us what you did!
      value: "Inserted a space after statement"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true